# Generated by Django 3.2.4 on 2021-06-27 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image_url',
            new_name='Link to Profile Image',
        ),
    ]
