# Generated by Django 3.2.5 on 2021-07-07 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_auto_20210707_1051'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhoneImages',
            new_name='PhoneImage',
        ),
    ]
