# Generated by Django 3.2.4 on 2021-06-27 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_rename_link_to_image_note_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='image_url',
            new_name='Link to Image',
        ),
    ]
