# Generated by Django 3.2.3 on 2021-07-22 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythons_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='id',
            new_name='user',
        ),
    ]
