# Generated by Django 3.2.3 on 2021-05-21 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='phone_model',
            new_name='model',
        ),
    ]
